# Generated by Django 5.2.11 on 2026-03-20 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriAlimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Refeicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('pequeno_almoco', 'Pequeno-almoço'), ('almoco', 'Almoço'), ('jantar', 'Jantar'), ('lanche', 'Lanche'), ('outro', 'Outro')], max_length=20)),
                ('hora', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('calorias_por_100g', models.FloatField()),
                ('proteina_g', models.FloatField(default=0.0)),
                ('hidratos_g', models.FloatField(default=0.0)),
                ('gordura_g', models.FloatField(default=0.0)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='alimentos/')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alimentos', to='workshop.categorialimento')),
            ],
        ),
        migrations.CreateModel(
            name='Objetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calorias_alvo', models.FloatField()),
                ('proteina_alvo_g', models.FloatField(default=0.0)),
                ('hidratos_alvo_g', models.FloatField(default=0.0)),
                ('gordura_alvo_g', models.FloatField(default=0.0)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetivos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RefeicaoAlimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_g', models.FloatField()),
                ('alimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='workshop.alimento')),
                ('refeicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='workshop.refeicao')),
            ],
        ),
        migrations.CreateModel(
            name='RegistoDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('notas', models.TextField(blank=True)),
                ('agua_ml', models.FloatField(default=0.0)),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='refeicao',
            name='registo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refeicoes', to='workshop.registodiario'),
        ),
    ]
